### ISSUE TITLE
database doesnot exist

### ISSUE THREAD

**Issue by pax83** [tnayuki/uas2git#3]
I have next error then run on my ubuntu server:
```
root@win4740:/home/git_repos# uas2git Astro
Enter password for admin@localhost:
Initializing a git repository: 100.0% (elapsed: 0s)
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/postgresql_adapter.rb:891:in `rescue in connect': FATAL:  database "Astro" does not exist (ActiveRecord::NoDatabaseError)
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `connect'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection               '
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
        from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
        from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_handling.rb:140:in `retrieve_connection'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/connection_handling.rb:114:in `connection'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/model_schema.rb:214:in `columns'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/model_schema.rb:260:in `column_names'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/relation/calculations.rb:221:in `aggregate_column'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/relation/calculations.rb:244:in `execute_simple_calculation'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/relation/calculations.rb:216:in `perform_calculation'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/relation/calculations.rb:111:in `calculate'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/relation/calculations.rb:26:in `count'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0.rc1/lib/active_record/querying.rb:13:in `count'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/uas2git-0.9.9/lib/uas2git/migrator.rb:15:in `migrate!'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/uas2git-0.9.9/lib/uas2git/main.rb:42:in `run!'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/uas2git-0.9.9/bin/uas2git:7:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.1/bin/uas2git:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.1/bin/uas2git:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tnayuki** [comment]
Sorry for very very late response.
I fixed it at last.
